Mock the API in SubjectPicker tests (#2361)
The subject picker requests subjects from `/api/subjects/selection` so this PR mocks that URL with nock.

Fixes this warning when running the tests:
```
Error: Nock: No match for request {
  "method": "GET",
  "url": "https://panoptes-staging.zooniverse.org/api/subjects/selection?ids=1%2C2%2C3&workflow_id=123345&http_cache=true",
  "headers": {
    "accept-encoding": "gzip, deflate",
    "content-type": "application/json",
    "accept": "application/vnd.api+json; version=1",
    "authorization": "Bearer "
  }
}
```